/* v9 feature layer. Classic script so it can collaborate with app.js without a build step. */
var e90Profile=readV9Json('e90-profile',null);
var e90AnswerBank=readV9Json('e90-answer-bank',{});
var e90Errors=readV9Json('e90-error-log',{});
var e90Competency=readV9Json('e90-competency',{});
var e90QualitySessions=readV9Json('e90-quality-sessions',[]);
var e90ListeningState={day:0,level:1,attempts:{},revealed:{},transcriptOpened:false};
var e90ConversationState={day:0,branch:'',attempts:new Set(),hints:new Set(),completed:false};
var e90PronunciationLoop={active:false,text:'',rate:1};
var e90PracticeRecorder=null,e90PracticeStream=null,e90PracticeChunks=[],e90PracticeTarget='';

function readV9Json(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||'null');return value??fallback;}catch(error){return fallback;}}
function writeV9Json(key,value){localStorage.setItem(key,JSON.stringify(value));}
function downloadV9(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function v9Pair(en,vi){return {en,vi};}
function escapeAttrV9(value){return escapeHtml(value).replace(/`/g,'&#096;');}

function migrateV8Data(){
  if(localStorage.getItem('e90-data-version')==='9') return;
  const oldPhrasebook=readV9Json('e90-phrasebook',{}),nextPhrasebook={};
  Object.entries(oldPhrasebook).forEach(([phrase,value])=>{
    const existing=value&&typeof value==='object'?value:{vi:typeof value==='string'?value:E90_VI.phrases[phrase]||''};
    nextPhrasebook[phrase]={vi:existing.vi||E90_VI.phrases[phrase]||'',stage:Number(existing.stage)||0,nextReview:Number(existing.nextReview)||Date.now(),reviews:Number(existing.reviews)||0,auto:!!existing.auto,skills:existing.skills&&typeof existing.skills==='object'?existing.skills:{}};
  });
  writeV9Json('e90-phrasebook',nextPhrasebook);
  const meta=readV9Json('e90-recording-meta',{});
  Object.values(meta).forEach(day=>{if(day&&day.createdAt&&!day.slots) day.slots={A:{duration:day.duration||0,createdAt:day.createdAt,rubric:day.rubric||{}}};if(day&&!day.best&&day.slots?.A) day.best='A';});
  writeV9Json('e90-recording-meta',meta);
  localStorage.setItem('e90-data-version','9');
}

function renderConversationExperience(lesson){
  const data=lesson.v9.conversation;
  if(e90ConversationState.day!==lesson.day)e90ConversationState={day:lesson.day,branch:'',attempts:new Set(),hints:new Set(),completed:false};
  document.getElementById('conversationContext').innerHTML=translationItem(data.context,'conversation-context',audioButton(data.context.en,'Nghe bối cảnh'));
  const container=document.getElementById('conversation');
  if(!e90ConversationState.branch){
    container.innerHTML=`<div class="branch-picker"><h3>Chọn cách bạn muốn phản hồi</h3><p class="small">Mỗi nhánh dẫn đến một kết quả công việc khác nhau.</p><div class="branch-options">${Object.entries(data.branches).map(([key,branch])=>`<div class="branch-choice">${audioButton(branch.opening.en,'Nghe câu mở đầu')}<button class="branch-option" onclick="chooseConversationBranch('${key}')"><b>${escapeHtml(branch.label.vi)}</b><span>${escapeHtml(branch.label.en)}</span></button></div>`).join('')}</div></div>`;
    document.getElementById('conversationProgress').textContent='Chưa chọn nhánh';return;
  }
  const branch=data.branches[e90ConversationState.branch];
  if(e90ConversationState.completed){container.innerHTML=conversationSummaryHtml(branch);document.getElementById('conversationProgress').textContent='Đã hoàn thành';return;}
  const allAnswered=e90ConversationState.attempts.size===branch.turns.length;
  container.innerHTML=`<div class="selected-branch"><b>${escapeHtml(branch.label.vi)}</b><button class="secondary" onclick="retryConversationBranch()">Đổi nhánh</button></div>${branch.turns.map((turn,index)=>renderV9ConversationTurn(turn,index,branch.turns.length)).join('')}${allAnswered?'<div class="conversation-finish"><p>Bạn có thể xem lại các gợi ý, rồi chốt kết quả hội thoại.</p><button class="primary" onclick="finishV9Conversation()">Chốt hội thoại & xem tóm tắt</button></div>':''}`;
  updateV9ConversationProgress(branch.turns.length);
}
function chooseConversationBranch(key){e90ConversationState.branch=key;e90ConversationState.attempts=new Set();e90ConversationState.hints=new Set();e90ConversationState.completed=false;renderConversationExperience(lessons[current-1]);setTimeout(()=>startV9ConversationPrompt(0),150);}
function renderV9ConversationTurn(turn,index,total){
  const attempted=e90ConversationState.attempts.has(index),active=index===0||e90ConversationState.attempts.has(index-1);
  return `<section class="conversation-turn${active?'':' locked-turn'}" id="v9ConversationTurn${index}"><div class="conversation-turn-heading"><b>Lượt ${index+1}/${total}</b><span>${attempted?'Đã trả lời':active?'Đến lượt bạn':'Đang khóa'}</span></div><div class="conversation-line from-partner"><div class="speaker-avatar">Đ</div><div class="conversation-bubble"><div class="speaker-name">Đồng nghiệp</div>${translationItem(v9Pair(turn.prompt.en,turn.prompt.vi),'conversation-sentence',audioButton(turn.prompt.en,'Nghe câu tiếp theo'))}</div></div><div class="conversation-response-zone"><b>${escapeHtml(turn.prompt.vi)}</b><p class="small">Tự trả lời trước. Gợi ý chỉ mở sau khi bạn xác nhận đã nói.</p><div class="conversation-turn-actions"><button class="primary" ${active?'':'disabled'} onclick="startV9ConversationPrompt(${index})">▶ Nghe + chuẩn bị</button><button class="secondary" ${active?'':'disabled'} onclick="startV9Recording(${index})">🎤 Ghi câu trả lời</button><button class="secondary" ${active?'':'disabled'} onclick="markV9ConversationAttempt(${index})">Tôi đã trả lời</button></div><div id="v9ConversationStatus${index}" class="small"></div><button class="conversation-reveal" id="v9ConversationReveal${index}" onclick="revealV9ConversationHint(${index})" ${attempted?'':'disabled'}>${attempted?'💡 Xem Phrase gợi ý & câu mẫu':'🔒 Trả lời trước để mở'}</button><div id="v9ConversationAnswer${index}" hidden><div class="conversation-hint">${translationItem(v9Pair(turn.phrase,E90_VI.phrases[turn.phrase]),'conversation-sentence',audioButton(turn.phrase))}</div>${translationItem(v9Pair(turn.response.en,turn.response.vi),'conversation-sentence',audioButton(turn.response.en))}</div></div></section>`;
}
function startV9ConversationPrompt(index){const turn=lessons[current-1].v9.conversation.branches[e90ConversationState.branch].turns[index],status=document.getElementById(`v9ConversationStatus${index}`);if(status)status.textContent='Đang nghe…';speak(turn.prompt.en,.9,()=>{let n=5;if(status)status.textContent=`Chuẩn bị: ${n} giây`;const timer=setInterval(()=>{n--;if(n>0){if(status)status.textContent=`Chuẩn bị: ${n} giây`;}else{clearInterval(timer);if(status)status.textContent='Hãy trả lời ngay.';}},1000);});}
function markV9ConversationAttempt(index){e90ConversationState.attempts.add(index);renderConversationExperience(lessons[current-1]);setTimeout(()=>document.getElementById(`v9ConversationTurn${index+1}`)?.scrollIntoView({behavior:'smooth',block:'center'}),50);}
function finishV9Conversation(){const branch=lessons[current-1].v9.conversation.branches[e90ConversationState.branch];if(!branch||e90ConversationState.attempts.size!==branch.turns.length)return;e90ConversationState.completed=true;saveConversationEvidence(branch);renderConversationExperience(lessons[current-1]);}
function revealV9ConversationHint(index){if(!e90ConversationState.attempts.has(index))return;e90ConversationState.hints.add(index);const answer=document.getElementById(`v9ConversationAnswer${index}`),button=document.getElementById(`v9ConversationReveal${index}`);if(answer)answer.hidden=false;if(button)button.hidden=true;}
function retryConversationBranch(){e90ConversationState.branch='';e90ConversationState.completed=false;e90ConversationState.attempts=new Set();e90ConversationState.hints=new Set();renderConversationExperience(lessons[current-1]);}
function conversationSummaryHtml(branch){const phrases=branch.turns.map(turn=>turn.phrase);return `<div class="conversation-summary"><div class="tagline">KẾT QUẢ HỘI THOẠI</div><h3>${escapeHtml(branch.label.vi)}</h3>${translationItem(branch.outcome,'conversation-outcome',audioButton(branch.outcome.en))}<div class="summary-stats"><div><b>${branch.turns.length-e90ConversationState.hints.size}</b><span>lượt không cần gợi ý</span></div><div><b>${branch.turns.length}</b><span>Phrase đã luyện</span></div></div><div class="summary-phrases">${phrases.map(phrase=>`<span>${escapeHtml(phrase)}</span>`).join('')}</div><button class="primary" onclick="retryConversationBranch()">↻ Luyện lại theo nhánh khác</button></div>`;}
function updateV9ConversationProgress(total){document.getElementById('conversationProgress').textContent=`${e90ConversationState.attempts.size}/${total} lượt đã trả lời`;}
function saveConversationEvidence(branch){const log=readV9Json('e90-conversation-evidence',[]);log.unshift({day:current,date:Date.now(),branch:e90ConversationState.branch,outcome:branch.outcome.vi,withoutHint:branch.turns.length-e90ConversationState.hints.size,phrases:branch.turns.map(turn=>turn.phrase)});writeV9Json('e90-conversation-evidence',log.slice(0,100));}

function renderListeningLadder(lesson){
  if(e90ListeningState.day!==lesson.day)e90ListeningState={day:lesson.day,level:1,attempts:{},revealed:{},transcriptOpened:false};
  const labels=['Không nhìn chữ','Nghe theo đoạn','Transcript English','Dịch tiếng Việt'];
  document.getElementById('listeningLevels').innerHTML=labels.map((label,index)=>`<button class="${e90ListeningState.level===index+1?'active':''}" ${index+1>maxListeningLevel()?'disabled':''} onclick="setListeningLevel(${index+1})"><span>${index+1}</span>${label}</button>`).join('');
  const stage=document.getElementById('listeningStage'),level=e90ListeningState.level;
  if(level===1)stage.innerHTML=`<p>Nghe toàn bộ bài mà không nhìn chữ. Sau đó trả lời câu hỏi ý chính.</p><button class="primary" onclick="speakListeningSequence()">▶ Nghe toàn bài</button>${listeningQuestionHtml(lesson.v9.questions[0],0)}`;
  if(level===2)stage.innerHTML=`<div class="speed-picker">Tốc độ: ${[.75,1,1.15].map(rate=>`<button onclick="setLadderRate(${rate})" class="${Number(sessionStorage.getItem('e90-listening-rate')||1)===rate?'active':''}">${String(rate).replace('.',',')}×</button>`).join('')}</div><div class="listening-segments">${lesson.v9.listening.map((item,index)=>`<div><span>${index+1}</span><div><b>${escapeHtml(item.en)}</b></div><button onclick="playListeningSentence(${index})">▶ Nghe</button><button onclick="playListeningSentence(${index},true)">↻ Lặp</button></div>`).join('')}</div>${listeningQuestionHtml(lesson.v9.questions[1],1)}`;
  if(level===3){e90ListeningState.transcriptOpened=true;stage.innerHTML=`<p>Nhấn từng câu để nghe. Phrase của ngày được đánh dấu.</p><div class="listening-transcript">${lesson.v9.listening.map((item,index)=>`<button id="transcriptSentence${index}" class="transcript-sentence${lesson.phrases.includes(item.en)?' useful':''}" onclick="playListeningSentence(${index})"><span>${escapeHtml(item.en)}</span><i>▶</i></button>`).join('')}</div>${listeningQuestionHtml(lesson.v9.questions[2],2)}`;}
  if(level===4)stage.innerHTML=`<p>Mở bản dịch từng câu sau khi đã xem transcript tiếng Anh.</p><div>${lesson.v9.listening.map(item=>translationItem(item,'listening-translation',audioButton(item.en))).join('')}</div>${listeningQuestionHtml(lesson.v9.questions[3],3,true)}`;
}
function maxListeningLevel(){if(e90ListeningState.attempts[2])return 4;if(e90ListeningState.attempts[1])return 3;if(e90ListeningState.attempts[0])return 2;return 1;}
function setListeningLevel(level){if(level<=maxListeningLevel()){e90ListeningState.level=level;renderListeningLadder(lessons[current-1]);}}
function listeningQuestionHtml(question,index,dictation=false){const attempted=e90ListeningState.attempts[index],revealed=e90ListeningState.revealed[index];return `<div class="listening-question"><div class="tagline">${question.type==='main'?'CÂU HỎI Ý CHÍNH':question.type==='detail'?'CÂU HỎI CHI TIẾT':question.type==='inference'?'CÂU HỎI SUY LUẬN':'DICTATION'}</div>${translationItem(question.q,'listening-prompt',audioButton(dictation?question.answer.en:question.q.en,dictation?'Nghe câu dictation':'Nghe câu hỏi'))}<textarea id="listeningAnswer${index}" placeholder="Trả lời trước khi xem đáp án…" oninput="unlockListeningAnswer(${index},this.value)">${escapeHtml(e90ListeningState.attempts[index]||'')}</textarea><button id="listeningReveal${index}" class="secondary" onclick="revealListeningAnswer(${index})" ${attempted?'':'disabled'}>${attempted?'Xem đáp án':'🔒 Nhập câu trả lời trước'}</button><div id="listeningCorrect${index}" ${revealed?'':'hidden'}>${translationItem(question.answer,'correct-answer',audioButton(question.answer.en))}</div>${attempted&&index<3?`<button class="primary" onclick="setListeningLevel(${index+2})">Tiếp tục tầng ${index+2} →</button>`:''}</div>`;}
function unlockListeningAnswer(index,value){if(!value.trim())return;e90ListeningState.attempts[index]=value;const button=document.getElementById(`listeningReveal${index}`);if(button){button.disabled=false;button.textContent='Xem đáp án';}renderListeningLadder(lessons[current-1]);}
function revealListeningAnswer(index){if(!e90ListeningState.attempts[index])return;e90ListeningState.revealed[index]=true;renderListeningLadder(lessons[current-1]);}
function setLadderRate(rate){sessionStorage.setItem('e90-listening-rate',rate);renderListeningLadder(lessons[current-1]);}
function speakListeningSequence(){speak(lessons[current-1].listening,Number(sessionStorage.getItem('e90-listening-rate')||1));}
function playListeningSentence(index,loop=false){const item=lessons[current-1].v9.listening[index],rate=Number(sessionStorage.getItem('e90-listening-rate')||1);document.querySelectorAll('.transcript-sentence').forEach((el,i)=>el.classList.toggle('playing',i===index));speak(item.en,rate,()=>{document.getElementById(`transcriptSentence${index}`)?.classList.remove('playing');if(loop)window.setTimeout(()=>playListeningSentence(index,false),350);});}

function renderPronunciationLab(lesson){document.getElementById('pronunciationLab').innerHTML=lesson.v9.pronunciation.map((item,index)=>{const phrase=lesson.phrases[index];return `<article class="pronunciation-item"><div>${translationItem(v9Pair(phrase,E90_VI.phrases[phrase]),'pronunciation-phrase',audioButton(phrase))}</div><div class="chunk-line">${item.chunks.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>')}</div><p>${escapeHtml(item.noteVi)}</p><div class="pronunciation-actions"><button onclick="speak(${JSON.stringify(phrase)},.75)">0,75×</button><button onclick="speak(${JSON.stringify(phrase)},1)">1×</button><button onclick="togglePronunciationLoop(${JSON.stringify(phrase)},this)">↻ Loop</button><button onclick="startPracticeRecording('pron-${current}-${index}')">🎤 Ghi âm</button><button onclick="alternatePronunciation(${JSON.stringify(phrase)},'pron-${current}-${index}')">⇄ Nghe xen kẽ</button></div><audio id="practiceAudio-pron-${current}-${index}" controls hidden></audio></article>`;}).join('');}
function togglePronunciationLoop(text,button){if(e90PronunciationLoop.active&&e90PronunciationLoop.text===text){e90PronunciationLoop.active=false;stopSpeak();button.classList.remove('active');return;}e90PronunciationLoop={active:true,text,rate:.75};button.classList.add('active');const play=()=>{if(!e90PronunciationLoop.active||e90PronunciationLoop.text!==text)return;speak(text,.75,()=>setTimeout(play,500));};play();}
async function startPracticeRecording(target){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return alert('Trình duyệt này không hỗ trợ ghi âm.');if(e90PracticeRecorder?.state==='recording'){e90PracticeRecorder.stop();return;}try{e90PracticeTarget=target;e90PracticeStream=await navigator.mediaDevices.getUserMedia({audio:true});e90PracticeChunks=[];e90PracticeRecorder=new MediaRecorder(e90PracticeStream);e90PracticeRecorder.ondataavailable=e=>{if(e.data.size)e90PracticeChunks.push(e.data);};e90PracticeRecorder.onstop=async()=>{e90PracticeStream?.getTracks().forEach(track=>track.stop());const blob=new Blob(e90PracticeChunks,{type:e90PracticeRecorder.mimeType||'audio/webm'});await saveRecording('practice',target,blob);const audio=document.getElementById(`practiceAudio-${target}`);if(audio){audio.src=URL.createObjectURL(blob);audio.hidden=false;}e90PracticeRecorder=null;if(target.startsWith('conversation-'))markV9ConversationAttempt(Number(target.split('-').pop()));};e90PracticeRecorder.start();setTimeout(()=>{if(e90PracticeRecorder?.state==='recording')e90PracticeRecorder.stop();},30000);}catch(error){alert('Không thể truy cập micro.');}}
async function alternatePronunciation(text,target){speak(text,.85,async()=>{const blob=await getRecording('practice',target);if(!blob)return;const audio=new Audio(URL.createObjectURL(blob));audio.play();audio.onended=()=>URL.revokeObjectURL(audio.src);});}

function dayErrors(day=current){return e90Errors[day]||(e90Errors[day]=[]);}
function renderDailyErrors(){const errors=dayErrors();document.getElementById('dailyErrors').innerHTML=errors.length?errors.map((error,index)=>errorRowHtml(error,index)).join(''):'<p class="empty-state">Chưa có lỗi nào được lưu cho ngày này.</p>';}
function errorRowHtml(error,index){return `<article class="error-row ${error.fixed?'fixed':''}"><label>Câu của tôi<textarea onchange="updateError(${index},'mine',this.value)">${escapeHtml(error.mine||'')}</textarea></label><label>Câu tốt hơn<textarea onchange="updateError(${index},'better',this.value)">${escapeHtml(error.better||'')}</textarea></label><label>Nghĩa tiếng Việt<input value="${escapeAttrV9(error.betterVi||'')}" onchange="updateError(${index},'betterVi',this.value)"></label><label>Lý do ngắn<input value="${escapeAttrV9(error.reason||'')}" onchange="updateError(${index},'reason',this.value)"></label><label>Nhóm lỗi<select onchange="updateError(${index},'group',this.value)">${['Từ vựng','Ngữ pháp gây hiểu nhầm','Phát âm','Mạch lạc','Tương tác'].map(group=>`<option${error.group===group?' selected':''}>${group}</option>`).join('')}</select></label><div class="error-actions"><button onclick="speak(${JSON.stringify(error.better||'')},.9)" ${error.better?'':'disabled'}>▶ Nghe câu tốt hơn</button><button onclick="startPracticeRecording('error-${current}-${index}')">🎤 Nói lại / dừng</button><button onclick="toggleErrorFixed(${index})">${error.fixed?'✓ Đã sửa':'Đánh dấu đã sửa'}</button><button onclick="removeError(${index})">Xóa</button></div><audio id="practiceAudio-error-${current}-${index}" controls hidden></audio></article>`;}
function addErrorRow(){const errors=dayErrors();if(errors.length>=3)return alert('Mỗi bài nói lưu tối đa 3 lỗi quan trọng.');errors.push({mine:'',better:'',betterVi:'',reason:'',group:'Từ vựng',fixed:false,createdAt:Date.now()});saveErrors();renderDailyErrors();}
function updateError(index,key,value){const error=dayErrors()[index];if(!error)return;error[key]=value;error.updatedAt=Date.now();if((key==='better'||key==='betterVi')&&error.better?.trim()){E90_VI.phrases[error.better.trim()]=error.betterVi?.trim()||`Câu cải thiện từ Ngày ${current}`;E90_VI.phraseExamples[error.better.trim()]=[v9Pair(`New client context: ${error.better.trim()}`,`Bối cảnh khách hàng mới: ${error.betterVi?.trim()||'hãy diễn đạt câu này theo tình huống mới'}`)];ensurePhraseEntry(error.better.trim(),true);savePhrasebook();}saveErrors();}
function toggleErrorFixed(index){const error=dayErrors()[index];if(error){error.fixed=!error.fixed;saveErrors();renderDailyErrors();}}
function removeError(index){dayErrors().splice(index,1);saveErrors();renderDailyErrors();}
function saveErrors(){writeV9Json('e90-error-log',e90Errors);}

var e90Axes=[['range','Range','Vận dụng được nhiều cách diễn đạt phù hợp với tình huống.'],['accuracy','Accuracy','Diễn đạt đủ chính xác để người nghe hiểu đúng.'],['fluency','Fluency','Duy trì nhịp nói và tự sửa mà không phải bắt đầu lại.'],['interaction','Interaction','Phản hồi, hỏi lại và cùng người khác tiến đến quyết định.'],['coherence','Coherence','Sắp xếp ý rõ ràng và kết thúc bằng bước tiếp theo.']];
function renderCompetency(){const recordings=readV9Json('e90-recording-meta',{}),conv=readV9Json('e90-conversation-evidence',[]);return `<div class="notice">Đây là dashboard tự đánh giá dựa trên bằng chứng luyện tập, không phải chứng chỉ CEFR chính thức.</div><div class="competency-grid">${e90Axes.map(([key,label,canDo])=>{const evidence=latestAxisEvidence(key,recordings,conv),state=e90Competency[key]||{};return `<article class="card competency-card"><h2>${label}</h2><p>${canDo}</p><label>Mức hiện tại<select onchange="setCompetency('${key}','level',this.value)">${['Đang hình thành','Có thể làm với chuẩn bị','Có thể làm độc lập','Ổn định trong tình huống mới'].map(level=>`<option${state.level===level?' selected':''}>${level}</option>`).join('')}</select></label><dl><dt>Bằng chứng gần nhất</dt><dd>${escapeHtml(evidence.text)}</dd><dt>Ngày luyện gần nhất</dt><dd>${evidence.date?new Date(evidence.date).toLocaleDateString('vi-VN'):'Chưa có'}</dd><dt>Bản ghi tốt nhất liên quan</dt><dd>${escapeHtml(evidence.recording)}</dd><dt>Hành động tiếp theo</dt><dd>${escapeHtml(nextAxisAction(key))}</dd></dl></article>`;}).join('')}</div>`;}
function latestAxisEvidence(key,recordings,conv){const best=Object.entries(recordings).reverse().find(([,meta])=>meta.best&&meta.slots?.[meta.best]);if(key==='interaction'&&conv[0])return{text:`Day ${conv[0].day}: ${conv[0].withoutHint} lượt không cần gợi ý`,date:conv[0].date,recording:'Bản ghi hội thoại trong phiên'};if(best){const [day,meta]=best,slot=meta.best;return{text:`Tự đánh giá bản ${slot}: ${JSON.stringify(meta.slots[slot].rubric||{})}`,date:meta.slots[slot].createdAt,recording:`Day ${day} — bản ${slot}`};}return{text:'Chưa có bằng chứng. Hoàn thành một bản ghi A/B/C.',date:0,recording:'Chưa chọn'};}
function nextAxisAction(key){return {range:'Dùng 3 Phrase yếu trong một tình huống mới.',accuracy:'Lưu và nói lại một câu tốt hơn trong Sổ lỗi.',fluency:'Ghi bản C 60 giây mà không bắt đầu lại.',interaction:'Hoàn thành một nhánh hội thoại không mở gợi ý.',coherence:'Dùng framework và chốt owner + deadline.'}[key];}
function setCompetency(key,field,value){e90Competency[key]=e90Competency[key]||{};e90Competency[key][field]=value;e90Competency[key].updatedAt=Date.now();writeV9Json('e90-competency',e90Competency);}

var e90AnswerTypes=[['intro','Giới thiệu bản thân'],['work','Công việc hiện tại'],['project','Dự án'],['achievement','Thành tựu'],['failure','Thất bại và bài học'],['strength','Điểm mạnh'],['weakness','Điểm yếu'],['goal','Mục tiêu nghề nghiệp'],['interview','Câu hỏi phỏng vấn']];
function renderAnswerBank(){return `<div class="answer-bank">${e90AnswerTypes.map(([key,label])=>{const item=e90AnswerBank[key]||{draft:'',improved:'',history:[],recording:''};return `<article class="card answer-item"><h2>${label}</h2><label>Bản nháp<textarea onchange="saveAnswer('${key}','draft',this.value)">${escapeHtml(item.draft)}</textarea></label><label>Phiên bản cải thiện<textarea onchange="saveAnswer('${key}','improved',this.value)">${escapeHtml(item.improved)}</textarea></label><div class="answer-actions"><button onclick="speak(${JSON.stringify(item.improved||item.draft)},.9)" ${(item.improved||item.draft)?'':'disabled'}>▶ Nghe</button><button onclick="startPracticeRecording('answer-${key}')">🎤 Ghi liên quan</button><button onclick="toggleAnswerHistory('${key}',this)">Lịch sử (${item.history?.length||0})</button></div><audio id="practiceAudio-answer-${key}" controls hidden></audio><div id="answerHistory-${key}" hidden>${(item.history||[]).map(version=>`<p><time>${new Date(version.at).toLocaleString('vi-VN')}</time> — ${escapeHtml(version.field)}: ${escapeHtml(version.value)}</p>`).join('')}</div></article>`;}).join('')}</div>`;}
function saveAnswer(key,field,value){const item=e90AnswerBank[key]||(e90AnswerBank[key]={draft:'',improved:'',history:[]});if(item[field]!==value&&item[field])item.history.unshift({at:Date.now(),field,value:item[field]});item[field]=value;item.updatedAt=Date.now();item.history=item.history.slice(0,20);writeV9Json('e90-answer-bank',e90AnswerBank);}
function toggleAnswerHistory(key,button){const el=document.getElementById(`answerHistory-${key}`);el.hidden=!el.hidden;button.textContent=el.hidden?`Lịch sử (${e90AnswerBank[key]?.history?.length||0})`:'Ẩn lịch sử';}

function softStreak(){const days=[...new Set(e90QualitySessions.map(ts=>new Date(ts).toISOString().slice(0,10)))].sort().reverse();if(!days.length)return 0;let score=1,previous=new Date(days[0]);for(const value of days.slice(1)){const date=new Date(value),gap=Math.round((previous-date)/86400000);if(gap<=2){score++;previous=date;}else break;}return score;}
function renderUtilities(){const due=typeof duePhrases==='function'?duePhrases().length:0;return `<div class="utilities-grid"><article class="card"><h2>🔀 Mixed Review</h2><p>Trộn Phrase nhiều chủ đề, ưu tiên mục yếu hoặc lâu chưa ôn và đặt vào tình huống mới.</p><p><b>${due}</b> mục đang đến hạn.</p><button class="primary" onclick="startMixedReview()">Bắt đầu Mixed Review</button></article><article class="card"><h2>🌿 Soft streak</h2><div class="soft-streak">${softStreak()} phiên chất lượng</div><p>Cho phép nghỉ một ngày. Chỉ tính phiên có hoạt động chủ động, không ép chuỗi tuyệt đối.</p></article><article class="card"><h2>🎙️ Audio offline</h2><p>Audio không nằm trong JSON. Bạn có thể tải riêng từng bản ghi từ Speaking Practice; metadata được giữ trong backup.</p><button onclick="exportAudioFiles()">Kiểm kê audio</button></article></div>`;}
function startMixedReview(){const entries=Object.entries(phrasebook).sort(([,a],[,b])=>(a.nextReview||0)-(b.nextReview||0));const selected=entries.slice(0,Math.min(20,entries.length)).map(([phrase])=>phrase);if(!selected.length)return alert('Hãy lưu ít nhất một Phrase trước.');openReview(false,selected);}

function openHub(view='competency'){stopSpeak();saveNote();document.getElementById('lessonView').hidden=true;document.getElementById('settingsPage').hidden=true;document.getElementById('reviewPage').hidden=true;document.getElementById('hubPage').hidden=false;const content=document.getElementById('hubContent');if(view==='competency'){document.getElementById('hubTitle').textContent='📊 Năng lực';document.getElementById('hubSubtitle').textContent='Theo dõi khả năng qua bằng chứng gần nhất, không dựa chủ yếu vào số ngày hoàn thành.';content.innerHTML=renderCompetency();}if(view==='answers'){document.getElementById('hubTitle').textContent='🗂️ Answer Bank';document.getElementById('hubSubtitle').textContent='Xây câu trả lời của riêng bạn và lưu lịch sử cải thiện.';content.innerHTML=renderAnswerBank();}if(view==='errors'){document.getElementById('hubTitle').textContent='🛠️ Sổ lỗi';document.getElementById('hubSubtitle').textContent='Các lỗi quan trọng đã lưu theo ngày.';content.innerHTML=Object.keys(e90Errors).length?Object.entries(e90Errors).map(([day,errors])=>`<section class="card"><h2>Day ${day}</h2>${errors.map(error=>`<p class="${error.fixed?'fixed-copy':''}"><b>${escapeHtml(error.mine)}</b> → ${escapeHtml(error.better)} <span>${escapeHtml(error.group)}</span></p>`).join('')}</section>`).join(''):'<div class="card">Chưa có lỗi nào.</div>';}if(view==='utilities'){document.getElementById('hubTitle').textContent='🧰 Tiện ích offline';document.getElementById('hubSubtitle').textContent='Ôn chuyển giao, soft streak và quản lý dữ liệu.';content.innerHTML=renderUtilities();}window.scrollTo({top:0,behavior:'smooth'});}
function closeHub(){document.getElementById('hubPage').hidden=true;document.getElementById('lessonView').hidden=false;render();}

function openOnboarding(editing=false){const dialog=document.getElementById('onboardingDialog');if(e90Profile){document.getElementById('profileRole').value=e90Profile.role||'';document.getElementById('profileIndustry').value=e90Profile.industry||'';document.getElementById('profilePartners').value=e90Profile.partners||'';document.getElementById('profileChallenge').value=e90Profile.challenge||'';document.getElementById('profileGoal').value=e90Profile.goal||'';}document.getElementById('onboardingCancel').hidden=false;dialog.showModal();}
function saveOnboarding(event){event.preventDefault();e90Profile={role:document.getElementById('profileRole').value.trim(),industry:document.getElementById('profileIndustry').value.trim(),partners:document.getElementById('profilePartners').value.trim(),challenge:document.getElementById('profileChallenge').value.trim(),goal:document.getElementById('profileGoal').value.trim(),updatedAt:Date.now()};writeV9Json('e90-profile',e90Profile);document.getElementById('onboardingDialog').close();renderProfileSettings();renderSidebar();}
function renderProfileSettings(){const el=document.getElementById('profileSettings');if(!el)return;el.innerHTML=e90Profile?`<p><b>${escapeHtml(e90Profile.role)}</b> • ${escapeHtml(e90Profile.industry)}</p><p>${escapeHtml(e90Profile.goal)}</p>`:'<p>Chưa thiết lập hồ sơ.</p>';}
function relevanceForLesson(lesson){if(!e90Profile)return 0;const text=`${e90Profile.role} ${e90Profile.industry} ${e90Profile.partners} ${e90Profile.challenge} ${e90Profile.goal}`.toLowerCase();const topic=lesson.title.toLowerCase();return ['interview','client','customer','project','presentation','technical','product','deadline','meeting'].reduce((score,word)=>score+(text.includes(word)&&topic.includes(word)?1:0),0);}

function setVoiceFilter(key,value){settings[`voice${key[0].toUpperCase()}${key.slice(1)}`]=value;saveSettings();loadVoiceOptions();}
function setAsrEnabled(enabled){settings.asrEnabled=enabled;saveSettings();if(enabled&&!('SpeechRecognition'in window)&&!('webkitSpeechRecognition'in window))alert('Trình duyệt này không cung cấp Speech Recognition. Ứng dụng vẫn hoạt động đầy đủ khi tắt.');}

function exportBackup(){saveNote();const data={app:'English 90',schemaVersion:9,exportedAt:new Date().toISOString(),localStorage:{}};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('e90-'))data.localStorage[key]=localStorage.getItem(key);}downloadV9(`english90-backup-${new Date().toISOString().slice(0,10)}.json`,new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));document.getElementById('backupStatus').textContent='Đã xuất backup JSON. Audio không được nhúng vào tệp này.';}
async function restoreBackup(file){if(!file)return;let data;try{data=JSON.parse(await file.text());}catch(error){return alert('Tệp JSON không hợp lệ.');}if(data.app!=='English 90'||!Number.isInteger(data.schemaVersion))return alert('Đây không phải backup English 90 hợp lệ.');if(data.schemaVersion>9)return alert(`Backup phiên bản ${data.schemaVersion} mới hơn ứng dụng hiện tại.`);if(!confirm(`Nhập backup schema v${data.schemaVersion} sẽ ghi đè dữ liệu English 90 hiện tại. Tiếp tục?`))return;Object.keys(localStorage).filter(key=>key.startsWith('e90-')).forEach(key=>localStorage.removeItem(key));Object.entries(data.localStorage||{}).filter(([key])=>key.startsWith('e90-')).forEach(([key,value])=>localStorage.setItem(key,String(value)));location.reload();}
async function exportAudioFiles(){const meta=readV9Json('e90-recording-meta',{}),items=[];for(const [day,dayMeta] of Object.entries(meta))for(const slot of Object.keys(dayMeta.slots||{})){try{const blob=await getRecording(Number(day),slot);if(blob)items.push({day:Number(day),slot,size:blob.size,type:blob.type});}catch(error){}}downloadV9(`english90-audio-manifest-${new Date().toISOString().slice(0,10)}.json`,new Blob([JSON.stringify({schemaVersion:9,note:'Audio blobs remain in IndexedDB. Use the player download control or browser save action for each recording.',items},null,2)],{type:'application/json'}));document.getElementById('backupStatus')?.replaceChildren(document.createTextNode(`Đã kiểm kê ${items.length} bản ghi. Audio vẫn được giữ an toàn trong IndexedDB.`));}

function renderWeeklyMission(lesson){const mission=lesson.v9.mission,profileDetail=e90Profile?` Liên hệ với vai trò ${e90Profile.role} và đối tác ${e90Profile.partners}.`:'';document.getElementById('weeklyMission').innerHTML=`<div class="mission-badge">Tuần ${mission.week} • ${escapeHtml(mission.type.vi)}</div>${translationItem(v9Pair(mission.prompt.en,mission.prompt.vi+profileDetail),'mission-copy',audioButton(mission.prompt.en))}`;}
function renderV9LessonTools(lesson){renderListeningLadder(lesson);renderPronunciationLab(lesson);renderDailyErrors();renderWeeklyMission(lesson);renderProfileSettings();document.getElementById('asrSetting')&&(document.getElementById('asrSetting').checked=!!settings.asrEnabled);if(!e90Profile&&document.readyState!=='loading'&&!sessionStorage.getItem('e90-onboarding-seen')){sessionStorage.setItem('e90-onboarding-seen','1');setTimeout(()=>openOnboarding(false),400);}}

async function startV9Recording(index){await startPracticeRecording(`conversation-${current}-${index}`);}

migrateV8Data();
window.addEventListener('DOMContentLoaded',()=>{if(!e90Profile&&!sessionStorage.getItem('e90-onboarding-seen')){sessionStorage.setItem('e90-onboarding-seen','1');setTimeout(()=>openOnboarding(false),400);}});
